# Prometheus Configuration for XO Game Monitoring

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "alert_rules.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

      - job_name: 'xo-game-app'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - xo-game
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: xo-game
          - source_labels: [__meta_kubernetes_pod_label_test]
            action: keep
            regex: stress
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: http
          - source_labels: [__meta_kubernetes_pod_ip]
            action: replace
            target_label: __address__
            regex: (.+)
            replacement: ${1}:8080
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

      - job_name: 'postgres'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - xo-game
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_component]
            action: keep
            regex: postgres-cluster
          - source_labels: [__meta_kubernetes_pod_ip]
            action: replace
            target_label: __address__
            regex: (.+)
            replacement: ${1}:5432
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

  alert_rules.yml: |
    groups:
      - name: xo-game-alerts
        rules:
          - alert: HighCPUUsage
            expr: rate(container_cpu_usage_seconds_total{pod=~"xo-game-stress-test-.*"}[5m]) > 0.8
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage detected"
              description: "Pod {{ $labels.pod }} has high CPU usage: {{ $value }}"

          - alert: HighMemoryUsage
            expr: container_memory_usage_bytes{pod=~"xo-game-stress-test-.*"} / container_spec_memory_limit_bytes > 0.8
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage detected"
              description: "Pod {{ $labels.pod }} has high memory usage: {{ $value }}"

          - alert: PodCrashLoopBackOff
            expr: kube_pod_status_phase{phase="Running"} == 0 and kube_pod_status_phase{phase="Pending"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Pod is not running"
              description: "Pod {{ $labels.pod }} is not in Running state"

          - alert: DatabaseConnectionFailure
            expr: up{job="postgres"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Database connection failed"
              description: "Cannot connect to PostgreSQL database"

          - alert: HighRequestLatency
            expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="xo-game-app"}[5m])) > 1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High request latency"
              description: "95th percentile latency is {{ $value }}s"
