apiVersion: apps/v1
kind: Deployment
metadata:
  name: xo-game-stress-test
  namespace: xo-game
  labels:
    app: xo-game
    component: app
    test: stress
spec:
  replicas: 8  # Increased to 8 replicas for higher load
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: xo-game
      component: app
      test: stress
  template:
    metadata:
      labels:
        app: xo-game
        component: app
        test: stress
    spec:
      containers:
        - name: xo-game-app
          image: xo-game:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              value: xo-game-postgres-cluster-service
            - name: DB_NAME
              value: xo_game
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: NODE_ENV
              value: production
            - name: SHARED_DATA_PATH
              value: /shared-data
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data
          resources:
            requests:
              memory: "512Mi"    # Increased for high load testing
              cpu: "500m"        # Increased for high load testing
            limits:
              memory: "1Gi"      # Increased for high load testing
              cpu: "1000m"       # Increased for high load testing
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
      restartPolicy: Always
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: xo-game-shared-data
